services:
  - type: web
    name: anonymous-message-board
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    env: node
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production